### ISSUE TITLE
Fix private code imported from SW lib

### ISSUE THREAD

**Issue by gaetbout** [keep-starknet-strange/alexandria#291]
// TODO Remove all done, it was copied from Starkware's library. There must be a better way
Fix this todo.

**Comment by gaetbout** [comment]
Ping

**Comment by gaetbout** [comment]
Pong

**Comment by gaetbout** [comment]
.

**Comment by harsh-ps-2003** [comment]
@gaetbout 
I see that because the [method is not public](tab:https://github.com/tarrencev/cairo/blob/31603449da58fbfeb452f79e3043a69692098cce/corelib/src/bytes_31.cairo#L113) in the core library, we have copied the method. I don't get `Fix private code imported` - its not imported, its defined in the file! `There must be a better way` - so we are trying to reimplement the methods in a better way, so there must be some problem with this copy pasted implementation. Can you elaborate? Sorry if the question is dumb, new to Starknet and Cairo in general! Thanks

**Comment by gaetbout** [comment]
My point is that we shouldn't have function copy pasted from SW repo. 
I believe reworking the logic, as you suggested, might be a correct fix.
Or we can ask SW to make that fn public

**Comment by harsh-ps-2003** [comment]
If SW can make the methods public, that would be sweet!

**Comment by gaetbout** [comment]
Ping

**Comment by gaetbout** [comment]
pong

**Comment by gaetbout** [comment]
Ding
